name: model-daibetes-outcome
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    # optionally use a convenient Ubuntu LTS + DVC + CML image
    container: ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
      # may need to setup NodeJS & Python3 on e.g. self-hosted
      # - uses: actions/setup-node@v3
      #   with:
      #     node-version: '16'
      # - uses: actions/setup-python@v4
      #   with:
      #     python-version: '3.x'
      - uses: iterative/setup-cml@v1
      - name: Train model
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}  # Make sure the token is available
        
        run: |
          # Your ML workflow goes here
          pip install -r requirements.txt
          python main.py
          echo "## MODEL METRICS" > report.md
          cat metrics.txt >> report.md

          # Publish feature importance and residuals plots in the report
          # Use inline images instead of cml publish
          echo "![Feature Importance](feature_importance.png)" >> report.md
          echo "![Residuals](residuals.png)" >> report.md

          # Create a comment with the report
          cml comment create report.md
           
